
SCHEME STDERR
AVERAGEFREQ ON
MINMAXFREQ ON
COLUMNCOUNTING STRICT
VERBOSE OFF

GENOMICCONTROL OFF
SEPARATOR TAB

MARKER   SNP
ALLELE   A1 A2
FREQLABEL     MAF
EFFECT   Effect
STDERR   SE
PVAL     Pval

PROCESS ../../EasyQC/results/CLEANED.HTN_Finngen_r7_GC.txt


GENOMICCONTROL OFF
SEPARATOR TAB

MARKER   SNP
ALLELE   A1 A2
FREQLABEL     MAF
EFFECT   Effect
STDERR   SE
PVAL     Pval

PROCESS ../../EasyQC/results/CLEANED.HTN_UKB_Watanabe.txt

OUTFILE meta.HTN.FinngenR7.UKBwatanabe. .tbl
ANALYZE HETEROGENEITY

QUIT