
SCHEME STDERR
AVERAGEFREQ ON
MINMAXFREQ ON
COLUMNCOUNTING STRICT
VERBOSE OFF

GENOMICCONTROL OFF
SEPARATOR TAB

MARKER   SNP
ALLELE   A1 A2
FREQLABEL     MAF
EFFECT   Effect
STDERR   SE
PVAL     Pval

PROCESS ../../EasyQC/results/CLEANED.T2D_Finngen_r7_GC.txt


GENOMICCONTROL OFF
SEPARATOR TAB

MARKER   SNP
ALLELE   A1 A2
FREQLABEL     MAF
EFFECT   Effect
STDERR   SE
PVAL     Pval

PROCESS ../../EasyQC/results/CLEANED.T2D_Mahajan2022.txt

GENOMICCONTROL ON
SEPARATOR TAB

MARKER   SNP
ALLELE   A1 A2
FREQLABEL     MAF
EFFECT   Effect
STDERR   SE
PVAL     Pval

PROCESS ../../EasyQC/results/CLEANED.T2D_MVP.txt

OUTFILE meta.T2D.FinngenR7.Mahajan2022.MVP. .tbl
ANALYZE HETEROGENEITY

QUIT